global:
  resolve_timeout: 5m

route:
  receiver: 'webhook'

receivers:
  - name: 'webhook'
    webhook_configs:
      - url: 'https://discord.com/api/webhooks/1152993205554520095/YSPANwI4DO3SE4xDAAODKf9CAqXZUwtXom2pDc9ve6-7x2EB-X8IBsW_W6n3YYR40dnF'
