global:
  scrape_interval: 15s

rule_files:
  - "alerts.rules"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'app-node'
    static_configs:
      - targets: ['app-node-test:80']
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app-java-servlet-test:8080']
